<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 30px;
            font-size: 12px;
        }
        h1 {
            text-align: center;
            color: #333;
            font-size: 22px;
            border-bottom: 3px solid #dc3545;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .info {
            text-align: center;
            margin-bottom: 25px;
            font-size: 11px;
            color: #666;
        }
        .info p {
            margin: 2px 0;
        }
        h2 {
            color: #333;
            font-size: 16px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 5px;
            margin: 25px 0 15px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        td {
            padding: 15px;
            text-align: center;
            border: 2px solid #ddd;
            width: 33.33%;
        }
        .green-bg {
            background-color: #d4edda;
        }
        .red-bg {
            background-color: #f8d7da;
        }
        .blue-bg {
            background-color: #d1ecf1;
        }
        .stat-label {
            font-size: 10px;
            font-weight: bold;
            color: #555;
            margin-bottom: 8px;
        }
        .stat-value {
            font-size: 26px;
            font-weight: bold;
            color: #000;
        }
        .summary {
            background-color: #f8f9fa;
            border-left: 4px solid #17a2b8;
            padding: 15px;
            margin: 20px 0;
        }
        .summary h3 {
            font-size: 14px;
            margin-bottom: 10px;
        }
        .summary p {
            margin: 8px 0;
            line-height: 1.5;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #ddd;
            text-align: center;
            font-size: 9px;
            color: #666;
        }
    </style>
</head>
<body>
    <h1>Medication Adherence Report</h1>
    
    <div class="info">
        <p><strong>Patient:</strong> {{ $patientName }}</p>
        <p><strong>Treatment Start Date:</strong> {{$treatmentStartFormatted}}</p>
        <p><strong>Period:</strong> {{ $currentMonth }}</p>
        <p><strong>Generated:</strong> {{ $reportDate }}</p>
    </div>

    <h2>Monthly Summary - {{ $currentMonth }}</h2>
    <table>
        <tr>
            <td class="green-bg">
                <div class="stat-label">DOSES TAKEN</div>
                <div class="stat-value">{{ $monthlyTaken }}</div>
            </td>
            <td class="red-bg">
                <div class="stat-label">DOSES MISSED</div>
                <div class="stat-value">{{ $monthlyMissed }}</div>
            </td>
            <td class="green-bg">
                <div class="stat-label">ADHERENCE RATE</div>
                <div class="stat-value">{{ $monthlyRate }}%</div>
            </td>
        </tr>
    </table>

    <h2>Overall Statistics - All Time</h2>
    <table>
        <tr>
            <td class="blue-bg">
                <div class="stat-label">TOTAL TAKEN</div>
                <div class="stat-value">{{ $totalTaken }}</div>
            </td>
            <td class="blue-bg">
                <div class="stat-label">TOTAL MISSED</div>
                <div class="stat-value">{{ $totalMissed }}</div>
            </td>
            <td class="blue-bg">
                <div class="stat-label">OVERALL RATE</div>
                <div class="stat-value">{{ $totalRate }}%</div>
            </td>
        </tr>
    </table>

    <h2>Summary &amp; Recommendations</h2>
    <div class="summary">
        <h3>Adherence Analysis</h3>
        <p><strong>Monthly Performance:</strong> You have taken {{ $monthlyTaken }} dose(s) and missed {{ $monthlyMissed }} dose(s) in {{ $currentMonth }}, resulting in {{ $monthlyRate }}% adherence.</p>
        <p><strong>Overall Performance:</strong> Your overall medication adherence rate is {{ $totalRate }}% with {{ $totalTaken }} total doses taken and {{ $totalMissed }} doses missed.</p>
        @if($totalRate >= 80)
            <p><strong>Excellent adherence!</strong> Keep up the great work maintaining your medication schedule.</p>
        @else
            <p><strong>Improvement needed.</strong> Please consult your healthcare provider to discuss strategies for improving medication adherence.</p>
        @endif
    </div>

    <div class="footer">
        <p><strong>Important:</strong> This report was automatically generated by the TB DOTS Patient Monitoring System</p>
        <p>For questions about your medication adherence, please consult your healthcare provider</p>
        <p>Copyright {{ date('Y') }} TB DOTS Patient Monitoring System</p>
    </div>
</body>
</html>