<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cured Patients</title>
    <style>
        body { 
            font-family: "Times New Roman", serif; 
            font-size: 13px; 
            color: #222; 
            margin: 40px;
            line-height: 1.5;
        }

        /* HEADER */
        .header {
            text-align: center;
            border-bottom: 2px solid #28a745;
            padding-bottom: 10px;
            margin-bottom: 25px;
        }
        .header h4 {
            margin: 0;
            font-size: 13px;
            color: #555;
        }
        .header h3 {
            margin: 8px 0 2px;
            font-size: 18px;
            font-weight: bold;
            text-transform: uppercase;
            color: #1f5124;
        }

        /* REPORT TITLE */
        .report-title {
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            text-transform: uppercase;
            color: #1d4120;
            margin: 20px 0 10px;
        }

        /* META INFO */
        .meta { 
            text-align: right;
            font-size: 12px;
            font-style: italic;
            color: #555;
            margin-bottom: 15px;
        }

        /* TABLE */
        table { 
            width: 100%; 
            border-collapse: collapse; 
            font-size: 13px;
        }
        th, td { 
            border: 1px solid #ccc; 
            padding: 8px 10px; 
        }
        th { 
            background: #28a745;
            color: #fff; 
            text-align: center;
            font-weight: bold;
            letter-spacing: 0.5px;
        }
        td { 
            text-align: center;
        }
        td:first-child {
            text-align: left;
            font-weight: 500;
        }
        tr:nth-child(even) td {
            background: #f8fdf8;
        }
        tr:hover td {
            background: #e9f7ec;
        }

        /* FOOTER */
        .footer {
            text-align: center;
            font-size: 11px;
            color: #777;
            margin-top: 25px;
            border-top: 1px solid #ccc;
            padding-top: 8px;
        }

        /* PRINT-FRIENDLY */
        @page {
            margin: 40px;
        }
    </style>
</head>
<body>
    
    <!-- HEADER -->
    <div class="header">
        <h4>Republic of the Philippines</h4>
        <h4>Municipality of Tagoloan</h4>
        <h3>TB DOTS Tagoloan</h3>
    </div>

    <!-- TITLE -->
    <div class="report-title">Cured Tuberculosis Patients Report</div>

    <!-- TABLE -->
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Sex</th>
                <th>Barangay</th>
                <th>TB Case #</th>
                <th>Treatment Start Date</th>
                <th>Treatment End Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($cured as $patient)
            <tr>
                <td>{{ $patient->pat_full_name }}</td>
                <td>{{ $patient->pat_age }}</td>
                <td>{{ $patient->pat_sex }}</td>
                <td>{{ $patient->barangay }}</td>
                <td>{{ $patient->diag_tb_case_no }}</td>
                <td>{{ \Carbon\Carbon::parse($patient->reg_start_date)->format('F j, Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($patient->outcome_date)->format('F j, Y') }}</td>
                <td>{{ $patient->outcome }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align:center;">No data found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
    <em>
        Generated by the <strong>TB DOTS Patient Monitoring System</strong> &mdash; 
        {{ \Carbon\Carbon::now()->format('F j, Y') }}
    </em>
    </div>

</body>
</html>
